name: CI

#запуск как на pull, так и на push запросах
on: [push, pull_request]

#глобальные переменные окружения
env:
  app_name: app_ver_${{ github.sha }}.exe

jobs:
  dependencies:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      #python и нужные библиотеки
      - name: Python setup
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      #используемые модули
      - name: Dependencies setup
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt
          
#   build_and_upload:
#     runs-on: ubuntu-20.04
#     needs: dependencies
#     steps:
#       - uses: actions/checkout@v2
      - name: Change output file name
        run: sed -i "s/name='main',/name='${{ env.app_name }}',/" main.spec
      #создаём исполняемый файл
      - name: Build application
        run: python -m PyInstaller --onefile --noconsole --add-data "web;web" --add-data "ph_dev.db;." main.py -n ${{ env.app_name }}
#         uses: JackMcKew/pyinstaller-action-linux@main
#         with:
#           path: ./
      
      #выгружаем артефакт
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.app_name }}
#           path: ./dist/linux
          path: ./dist
          retention-days: 90
