name: CI

#запуск как на pull, так и на push запросах
on: [push, pull_request]

#глобальные переменные окружения
env:
  app_name: app_ver_${{ github.sha }}.exe

jobs:
  dependencies:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
      #python и нужные библиотеки
      - name: Python setup
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      #используемые модули
      - name: Dependencies setup
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt
      #создаём исполняемый файл
      - name: Build application
        run: python -m PyInstaller --onefile --noconsole --add-data "web;web" --add-data "ph_dev.db;." main.py -n ${{ env.app_name }}
      
      #выгружаем артефакт
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.app_name }}
          path: ./dist
          retention-days: 90
