name: CI

#запуск как на pull, так и на push запросах
on: [push, pull_request]

#глобальные переменные окружения
env:
  app_name: app_ver_${{ github.sha }}

jobs:
  dependencies:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      #python и нужные библиотеки
      - name: Python setup
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      #используемые модули
      - name: Dependencies setup
        run: |
          pip install -r requirements.txt
          
  build_and_upload:
    runs-on: ubuntu-20.04
    needs: dependencies
    steps:
      #- uses: actions/checkout@v2
      #зависимость для создания исполняемого файла
      - name: Build application
        uses: JackMcKew/pyinstaller-action-windows@main
        with:
          path: ./
      - name: Dir
        run: |
          ls -la
          cd dist
          ls -la
      #создаём исполняемый файл
      
      #выгружаем артефакт
      - name: Upload artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: ${{ env.app_name }}
          path: ./dist/${{ env.app_name }}
          retention-days: 90
